name: update-typing-practice
on:
  workflow_dispatch:
    inputs:
      update_message:
        description: "update message from Shortcuts input"
        required: true
        type: string
jobs:
  update-typing-practice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup git config
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "weijianduan0302@gmail.com"
      - name: commit & push today's practice log
        run: |
          date=$(date '+%Y-%m-%d')
          IFS=',' read -ra array <<< "${{ inputs.update_message }}"

          for element in "${array[@]}"
          do
            updateMsg="| ${date} | ${{ inputs.update_message}} |"
            echo ${updateMsg} >> README.md
          done

          commitMsg="${date} ${{ inputs.update_message }}"
          git add README.md
          git commit -m "${commitMsg}"
          git push origin HEAD:main