name: update-typing-practice
on:
  workflow_dispatch:
    inputs:
      update_message:
        description: "update message from Shortcuts input"
        required: true
        type: string
jobs:
  update-typing-practice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup git config
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "weijianduan0302@gmail.com"
      - name: commit & push today's practice log
        run: |
          date=$(date '+%Y-%m-%d')
          commitMsg="${date} ${{ inputs.update_message}}"
          echo ${commitMsg}
          git commit --allow-empty -m "${commitMsg}"
          git push origin HEAD:main